apiVersion: apps/v1
kind: Deployment
metadata:
  name: netli-deployment
  labels:
    app: netli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netli
  template:
    metadata:
      labels:
        app: netli
    spec:
      containers:
      - name: netliserver
        image: suren2014/myimg
        ports:
        - containerPort: 80
